repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^custom_components/electrolux/

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: ^custom_components/electrolux/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        files: ^custom_components/electrolux/
        additional_dependencies:
          - homeassistant

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        args: [--cov=custom_components/electrolux, --cov-fail-under=70, -q]
        stages: [pre-push]
