"""Defined catalog of entities for robot vacuum type devices (PUREi9, Gordias, Cybele, 700series).

Different robot vacuum models use different API key names for equivalent concepts:
- PUREi9 (older):  robotStatus (int 1-14), CleaningCommand, batteryStatus, powerMode
- Gordias/Cybele/700series (newer):  state (string), cleaningCommand, batteryStatus,
                                      chargingStatus, vacuumMode

Because the catalog is matched against the device's actual capabilities, placing all
keys in one catalog is safe — each device will only expose its own subset.
"""

from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.components.switch import SwitchDeviceClass
from homeassistant.const import PERCENTAGE, EntityCategory

from ..const import BINARY_SENSOR, BUTTON, SWITCH
from ..model import ElectroluxDevice

# PUREi9 robotStatus integer values (from SDK rvc_config.py IS_DOCKED_MAP/IS_PAUSED_MAP)
# Keys are strings because value_mapping expects dict[float | str, str]
_PUREI9_ROBOT_STATUS_VALUES: dict[float | str, str] = {
    "1": "Cleaning",
    "2": "Paused cleaning",
    "3": "Spot cleaning",
    "4": "Paused spot cleaning",
    "5": "Zone cleaning",
    "6": "Paused zone cleaning",
    "7": "Collecting",
    "8": "Paused collecting",
    "9": "Docked",
    "10": "Sleeping",
    "11": "Error",
    "12": "Fully charged",
    "13": "Going home",
    "14": "End of life",
}

CATALOG_RVC: dict[str, ElectroluxDevice] = {
    # ── Battery ────────────────────────────────────────────────────────────────
    "batteryStatus": ElectroluxDevice(
        capability_info={"access": "read", "type": "int", "min": 1, "max": 6},
        device_class=SensorDeviceClass.BATTERY,
        unit=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:battery",
        friendly_name="Battery",
    ),
    # ── PUREi9 ─────────────────────────────────────────────────────────────────
    # Integer status (1-14); human-readable via value_mapping
    "robotStatus": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                str(k): {"name": v} for k, v in _PUREI9_ROBOT_STATUS_VALUES.items()
            },
        },
        device_class=SensorDeviceClass.ENUM,
        unit=None,
        entity_category=None,
        entity_icon="mdi:robot-vacuum",
        friendly_name="Robot Status",
        value_mapping=_PUREI9_ROBOT_STATUS_VALUES,
    ),
    # Cleaning command (read-write select)
    "CleaningCommand": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "play": {"icon": "mdi:play"},
                "stop": {"icon": "mdi:stop"},
                "pause": {"icon": "mdi:pause"},
                "home": {"icon": "mdi:home"},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:robot-vacuum",
        friendly_name="Cleaning Command",
    ),
    "dustbinStatus": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "NOTCONNECTED": {"name": "Not connected"},
                "CONNECTED": {"name": "Connected"},
                "FULL": {"name": "Full"},
                "EMPTY": {"name": "Empty"},
            },
        },
        device_class=SensorDeviceClass.ENUM,
        unit=None,
        entity_category=None,
        entity_icon="mdi:trash-can-outline",
        friendly_name="Dustbin Status",
        value_mapping={
            "NOTCONNECTED": "Not connected",
            "CONNECTED": "Connected",
            "FULL": "Full",
            "EMPTY": "Empty",
        },
    ),
    # Power/cleaning intensity mode.
    # The API reports an integer range (min=1, max=3 for 3-mode, min=1, max=2 for 2-mode).
    # Human-readable labels are confirmed by user reports:
    # - 3-mode devices (Pure i9.2): Eco / Standard / Power
    # - 2-mode devices (Pure i9): Eco / Power
    # See https://github.com/TTLucian/ha-electrolux/issues/81
    # The vacuum platform reads the device's actual min/max to build the
    # correct speed list per model and select the appropriate mapping.
    "powerMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "int",
            "min": 1,
            "max": 3,
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:speedometer",
        friendly_name="Power Mode",
        value_mapping={
            1: "Eco",
            2: "Standard",
            3: "Power",
        },
    ),
    # ── PUREi9 additional settings ─────────────────────────────────────────────
    # Eco mode (boolean switch — reduces suction to save battery)
    "ecoMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_platform=SWITCH,
        entity_icon="mdi:leaf",
        friendly_name="Eco Mode",
    ),
    # Mute (boolean switch — disables robot voice prompts)
    "mute": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_platform=SWITCH,
        entity_icon="mdi:volume-off",
        friendly_name="Mute",
    ),
    # ── PUREi9 maintenance counters (reported in m²) ──────────────────────────
    "mainBrushSqM": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="m²",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:brush",
        friendly_name="Main Brush Usage",
    ),
    "sideBrushSqM": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="m²",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:brush",
        friendly_name="Side Brush Usage",
    ),
    "filterSqM": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="m²",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:air-filter",
        friendly_name="Filter Usage",
    ),
    # ── Gordias / Cybele / 700series ────────────────────────────────────────────
    # String state (inProgress / goingHome / idle / paused / sleeping / …)
    "state": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "inProgress": {},
                "goingHome": {},
                "idle": {},
                "paused": {},
                "sleeping": {},
                "vacuuming": {},
                "mopping": {},
                "pitStop": {},
                "stationAction": {},
            },
        },
        device_class=SensorDeviceClass.ENUM,
        unit=None,
        entity_category=None,
        entity_icon="mdi:robot-vacuum",
        friendly_name="Cleaning State",
    ),
    # Charging status (string: idle / charging / fullyCharged)
    "chargingStatus": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "idle": {},
                "charging": {},
                "fullyCharged": {},
            },
        },
        device_class=SensorDeviceClass.ENUM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:battery-charging",
        friendly_name="Charging Status",
    ),
    # Cleaning command (Gordias/Cybele/700series naming)
    "cleaningCommand": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "startGlobalClean": {"icon": "mdi:play"},
                "stopClean": {"icon": "mdi:stop"},
                "pauseClean": {"icon": "mdi:pause"},
                "resumeClean": {"icon": "mdi:play-pause"},
                "startGoToCharger": {"icon": "mdi:home"},
                "startMoppingClean": {"icon": "mdi:water"},
                "startEdgeClean": {"icon": "mdi:square-outline"},
                "startPointClean": {"icon": "mdi:map-marker-radius"},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:robot-vacuum",
        friendly_name="Cleaning Command",
    ),
    # Vacuum cleaning mode (select)
    # Combined values from multiple models:
    # - Cybele: energySaving, max
    # - Gordias/700series: quiet, energySaving, standard, powerful
    "vacuumMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "quiet": {"icon": "mdi:volume-off"},
                "energySaving": {"icon": "mdi:leaf"},
                "standard": {"icon": "mdi:fan"},
                "max": {"icon": "mdi:flash"},
                "powerful": {"icon": "mdi:flash-alert"},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:speedometer",
        friendly_name="Vacuum Mode",
    ),
    "cleaningType": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:broom",
        friendly_name="Cleaning Type",
    ),
    "cleaningMode": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:play-circle",
        friendly_name="Cleaning Mode",
    ),
    "waterPumpRate": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"off": {}, "low": {}, "medium": {}, "high": {}, "max": {}},
        },
        device_class=SensorDeviceClass.ENUM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water-pump",
        friendly_name="Water Pump Rate",
    ),
    "waterStationAction": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"idle": {}, "drying": {}, "cleaning": {}},
        },
        device_class=SensorDeviceClass.ENUM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water",
        friendly_name="Water Station Action",
    ),
    "mopRoute": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:map-marker-path",
        friendly_name="Mop Route",
    ),
    "notificationEvent": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:bell-ring",
        friendly_name="Notification Event",
    ),
    "dirtCleanMode": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water-percent",
        friendly_name="Dirt Clean Mode",
    ),
    "faultCode": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=SensorDeviceClass.ENUM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle-outline",
        friendly_name="Fault Code",
    ),
    "filterUsage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="%",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:air-filter",
        friendly_name="Filter Usage",
    ),
    "cleanSize": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:map-marker-distance",
        friendly_name="Clean Size",
    ),
    "cleanTime": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:timer-outline",
        friendly_name="Clean Time",
    ),
    "dustbagUsage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="%",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:bag-personal",
        friendly_name="Dust Bag Usage",
    ),
    "dustboxUsage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="%",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:robot-vacuum",
        friendly_name="Dust Box Usage",
    ),
    "emptyingTime": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:trash-can-outline",
        friendly_name="Emptying Time",
    ),
    "mainBrushUsage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="%",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:brush",
        friendly_name="Main Brush Usage",
    ),
    "sideBrushUsage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="%",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:brush",
        friendly_name="Side Brush Usage",
    ),
    "mopUsage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="%",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:square-edit-outline",
        friendly_name="Mop Usage",
    ),
    "mopArmExtensionFreq": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:arm-flex",
        friendly_name="Mop Arm Extension Frequency",
    ),
    "mopDryTime": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="s",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:towel",
        friendly_name="Mop Dry Time",
    ),
    "mopWashFreqArea": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water",
        friendly_name="Mop Wash Frequency Area",
    ),
    "mopWashFreqTime": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="min",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:timer",
        friendly_name="Mop Wash Frequency Time",
    ),
    "mopWashFreqType": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:format-list-numbered",
        friendly_name="Mop Wash Frequency Type",
    ),
    "numberOfCleaningRepetitions": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:repeat",
        friendly_name="Cleaning Repetitions",
    ),
    "voiceVolume": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:volume-high",
        friendly_name="Voice Volume",
    ),
    "upgradeProgress": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="%",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:update",
        friendly_name="Upgrade Progress",
    ),
    "stationUpgradeStatus": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:server-network",
        friendly_name="Station Upgrade Status",
    ),
    "upgradeState": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:update",
        friendly_name="Upgrade State",
    ),
    "selectedRoomId": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:door-open",
        friendly_name="Selected Room Id",
    ),
    "maxUsageDustBox": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="%",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:robot-vacuum",
        friendly_name="Max Dust Box Usage",
    ),
    "maxUsageStationBag": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="%",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:bag-personal",
        friendly_name="Max Station Bag Usage",
    ),
    "autoDustCollection": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:robot-vacuum",
        friendly_name="Auto Dust Collection",
    ),
    "autoMopArmExtension": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:arm-flex",
        friendly_name="Auto Mop Arm Extension",
    ),
    "autoMopDry": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water-off",
        friendly_name="Auto Mop Dry",
    ),
    "autoMopWash": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water",
        friendly_name="Auto Mop Wash",
    ),
    "autoDetergentUsage": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:bottle-tonic",
        friendly_name="Auto Detergent Usage",
    ),
    "mopInstalled": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water",
        friendly_name="Mop Installed",
    ),
    "inCharger": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:power-plug",
        friendly_name="In Charger",
    ),
    "returnToWash": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:refresh",
        friendly_name="Return to Wash",
    ),
    "roomSelected": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:feature-search-outline",
        friendly_name="Room Selected",
    ),
    "carpetBoost": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flash",
        friendly_name="Carpet Boost",
    ),
    "carpetAvoid": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:carpet",
        friendly_name="Carpet Avoid",
    ),
    "carpetDisplay": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:monitor",
        friendly_name="Carpet Display",
    ),
    "obstacleAvoidance": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:radar",
        friendly_name="Obstacle Avoidance",
    ),
    "dndEnabled": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:moon-waning-crescent",
        friendly_name="Do Not Disturb Enabled",
    ),
    "dndDisableAirDry": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:air-filter",
        friendly_name="DND Disable Air Dry",
    ),
    "isDndPausingAirDry": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:pause",
        friendly_name="DND Pausing Air Dry",
    ),
    "multiFloorMap": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:home-map-marker",
        friendly_name="Multi-floor Map",
    ),
    "multiFloorMapAutoSwitch": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:autorenew",
        friendly_name="Multi-floor Map Auto Switch",
    ),
    "dndStartTime": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:clock-start",
        friendly_name="DND Start Time",
    ),
    "dndEndTime": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:clock-end",
        friendly_name="DND End Time",
    ),
    "dataModelVersion": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:code-braces",
        friendly_name="Data Model Version",
    ),
    "baseStationVersion": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:chip",
        friendly_name="Base Station Version",
    ),
    "deviceId": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:barcode",
        friendly_name="Device Id",
    ),
    "VmNo_MCU": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:chip",
        friendly_name="MCU Version",
    ),
    "VmNo_NIU": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:chip",
        friendly_name="NIU Version",
    ),
    "TimeZoneDaylightRule": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:clock",
        friendly_name="Time Zone Daylight Rule",
    ),
    "TimeZoneStandardName": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:clock",
        friendly_name="Time Zone Standard Name",
    ),
    # ── Gordias / 700series additional ─────────────────────────────────────────
    # Bin/tank configuration (which accessories are installed)
    "binTank": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "none": {"name": "None"},
                "dustBox": {"name": "Dust Box"},
                "waterTank": {"name": "Water Tank"},
                "both": {"name": "Both"},
            },
        },
        device_class=SensorDeviceClass.ENUM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:tray-full",
        friendly_name="Bin Tank",
        value_mapping={
            "none": "None",
            "dustBox": "Dust Box",
            "waterTank": "Water Tank",
            "both": "Both",
        },
    ),
    # Find-me / locate robot action (button)
    "findMe": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "values": {"findMe": {"icon": "mdi:map-marker-account"}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_platform=BUTTON,
        entity_icon="mdi:map-marker-account",
        friendly_name="Find Me",
    ),
    # Voice volume setting (Gordias string enum, distinct from voiceVolume number)
    "setVoiceVolume": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "mute": {"icon": "mdi:volume-off"},
                "low": {"icon": "mdi:volume-low"},
                "medium": {"icon": "mdi:volume-medium"},
                "high": {"icon": "mdi:volume-high"},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:volume-high",
        friendly_name="Voice Volume",
    ),
    # --- Pure i9 read-only map / cleaning-session data (#130) ---
    "persistentMapsCreated/mapId": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:map",
        friendly_name="Persistent Map ID",
    ),
    "cleaningSession/sessionId": ElectroluxDevice(
        capability_info={"access": "read", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Cleaning Session ID",
    ),
    "cleaningSession/completion": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flag-checkered",
        friendly_name="Cleaning Completion",
    ),
    "cleaningSession/areaCovered": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="m²",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:ruler-square",
        friendly_name="Area Covered",
    ),
    "mapData/robotPoseReliable": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:crosshairs-gps",
        friendly_name="Robot Pose Reliable",
    ),
    # Derived: number of zones on the persistent map (#130)
    "mapData/mapMatch/zones": ElectroluxDevice(
        capability_info={"access": "read", "type": "list"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:shape-outline",
        friendly_name="Map Zone Count",
    ),
    # Derived: last cleaning-session zone status summary (#130)
    "cleaningSession/zoneStatus": ElectroluxDevice(
        capability_info={"access": "read", "type": "list"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:map-marker-check",
        friendly_name="Cleaning Zone Status",
    ),
}
