"""Defined catalog of entities for washing machine type devices."""

from homeassistant.components.binary_sensor import BinarySensorDeviceClass
from homeassistant.components.button import ButtonDeviceClass
from homeassistant.components.number import NumberDeviceClass
from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.components.switch import SwitchDeviceClass
from homeassistant.const import EntityCategory, UnitOfMass, UnitOfTime, UnitOfVolume

from ..const import (
    AUTODOSE_DETERGENT_DUAL_OFF,
    AUTODOSE_DETERGENT_DUAL_ON,
    AUTODOSE_LINK_OFF,
    AUTODOSE_LINK_ON,
    AUTODOSE_OFF,
    AUTODOSE_SOFTENER_OFF,
    AUTODOSE_SOFTENER_ON,
)
from ..execute_command_states import WASHER_EXECUTE_STATES
from ..model import ElectroluxDevice

CATALOG_WM: dict[str, ElectroluxDevice] = {
    "userSelections/EWX1493A_preWashPhase": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-plus",
        friendly_name="Pre-Wash",
    ),
    # Basic controls
    "defaultExtraRinse": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"EXTRA_RINSE_1": {}, "EXTRA_RINSE_OFF": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "executeCommand": ElectroluxDevice(
        capability_info={
            "access": "write",
            "type": "string",
            "values": {
                "OFF": {},
                "ON": {},
                "PAUSE": {},
                "RESUME": {},
                "START": {},
                "STOPRESET": {},
            },
        },
        device_class=ButtonDeviceClass.RESTART,
        unit=None,
        entity_category=None,
        entity_icon="mdi:play-pause",
        available_when_states=WASHER_EXECUTE_STATES,
    ),
    # Cycle information
    "cyclePhase": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "ANTICREASE": {},
                "DRAIN": {},
                "DRY": {},
                "PREWASH": {},
                "RINSE": {},
                "SPIN": {},
                "STEAM": {},
                "WASH": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "cycleSubPhase": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "ADD_GARMENT": {},
                "RINSE": {},
                "RINSE_HOLD": {},
                "SOAKING": {},
                "WASH": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "measuredLoadWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.WEIGHT,
        unit=UnitOfMass.GRAMS,
        entity_category=None,
        entity_icon="mdi:weight",
        friendly_name="Measured Load Weight",
    ),
    # Door and lock status
    "doorState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"CLOSED": {}, "OPEN": {}},
        },
        device_class=BinarySensorDeviceClass.OPENING,
        unit=None,
        entity_category=None,
    ),
    "doorLock": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"LOCKING": {}, "OFF": {}, "ON": {}, "UNLOCKING": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:lock",
    ),
    # Time and duration controls
    "startTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "max": 72000,
            "min": 0,
            "step": 1800,
            "type": "number",
        },
        device_class=NumberDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=None,
        entity_icon="mdi:clock-start",
    ),
    "stopTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "max": 86400,
            "min": 0,
            "step": 1800,
            "type": "number",
        },
        device_class=NumberDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=None,
        entity_icon="mdi:clock-end",
        friendly_name="Stop Time",
    ),
    # Statistics and counters
    "totalWashCyclesCount": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
    ),
    "totalWashingTime": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=None,
        entity_icon="mdi:timelapse",
    ),
    # Load and weight sensors
    "fcOptisenseLoadWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.WEIGHT,
        unit=UnitOfMass.GRAMS,
        entity_category=None,
        entity_icon="mdi:weight",
    ),
    "washingNominalLoadWeight": ElectroluxDevice(
        capability_info={
            "access": "read",
            "max": 20000,
            "min": 0,
            "type": "number",
        },
        device_class=SensorDeviceClass.WEIGHT,
        unit=UnitOfMass.GRAMS,
        entity_category=None,
        entity_icon="mdi:weight",
    ),
    # Auto-dosing system
    "autoDosing/adTankAConfiguration": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"DETERGENT_DUAL": {}, "DISABLED": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Tank A Configuration",
    ),
    "autoDosing/adTankBConfiguration": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DETERGENT_DUAL": {},
                "DISABLED": {},
                "LINK": {},
                "SOFTENER": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Tank B Configuration",
    ),
    "autoDosing/adTankADetStandardDose": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 110,
            "max": 200,
            "min": 5,
            "step": 1,
            "type": "number",
        },
        device_class=None,
        unit="ml",
        entity_category=None,
        entity_icon="mdi:cup-water",
        friendly_name="Tank A Detergent Dose",
    ),
    "autoDosing/adTankBDetStandardDose": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 110,
            "max": 200,
            "min": 5,
            "step": 1,
            "type": "number",
        },
        device_class=None,
        unit="ml",
        entity_category=None,
        entity_icon="mdi:cup-water",
        friendly_name="Tank B Detergent Dose",
    ),
    "autoDosing/adTankBSoftStandardDose": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 25,
            "max": 100,
            "min": 5,
            "step": 1,
            "type": "number",
        },
        device_class=None,
        unit="ml",
        entity_category=None,
        entity_icon="mdi:cup-water",
        friendly_name="Tank B Softener Dose",
    ),
    # User selections
    "userSelections/steamValue": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": "STEAM_OFF",
            "type": "string",
            "values": {
                "STEAM_MAX": {},
                "STEAM_MED": {},
                "STEAM_MIN": {},
                "STEAM_OFF": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-partly-cloudy",
    ),
    "userSelections/timeManagerLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DAILY": {},
                "NORMAL": {},
                "SUPER_QUICK": {},
                "TIME_MANAGER_LEV_1": {},
                "TIME_MANAGER_LEV_4": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:speedometer",
    ),
    "userSelections/adTankASel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                AUTODOSE_DETERGENT_DUAL_OFF: {},
                AUTODOSE_DETERGENT_DUAL_ON: {},
                AUTODOSE_LINK_OFF: {},
                AUTODOSE_LINK_ON: {},
                AUTODOSE_OFF: {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Auto-Dose Tank A",
    ),
    "userSelections/adTankBSel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                AUTODOSE_DETERGENT_DUAL_OFF: {},
                AUTODOSE_DETERGENT_DUAL_ON: {},
                AUTODOSE_LINK_OFF: {},
                AUTODOSE_LINK_ON: {},
                AUTODOSE_OFF: {},
                AUTODOSE_SOFTENER_OFF: {},
                AUTODOSE_SOFTENER_ON: {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Auto-Dose Tank B",
    ),
    "userSelections/adFineTuneDetLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "FINE_TUNE_DET_LEV_1": {},
                "FINE_TUNE_DET_LEV_3": {},
                "FINE_TUNE_DET_LEV_5": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:tune",
        friendly_name="Detergent Fine Tune",
    ),
    "userSelections/adFineTuneSoftLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"FINE_TUNE_SOFT_LEV_1": {}, "FINE_TUNE_SOFT_NOT_AVAILABLE": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:tune",
        friendly_name="Softener Fine Tune",
    ),
    "userSelections/analogSpinSpeed": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "0_RPM": {},
                "400_RPM": {},
                "600_RPM": {},
                "800_RPM": {},
                "1000_RPM": {},
                "1200_RPM": {},
                "1400_RPM": {},
                "1600_RPM": {},
                "DISABLED": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:rotate-right",
    ),
    "userSelections/analogTemperature": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "20_CELSIUS": {},
                "30_CELSIUS": {},
                "40_CELSIUS": {},
                "50_CELSIUS": {},
                "60_CELSIUS": {},
                "90_CELSIUS": {},
                "95_CELSIUS": {},
                "COLD": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer",
    ),
    "userSelections/extraRinseNumber": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "NONE": {},
                "ONE": {},
                "TWO": {},
                "THREE": {},
                "PLUS_1_RINSE": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
        friendly_name="Extra Rinse Number",
    ),
    "userSelections/EWX1493A_anticreaseNoSteam": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:hanger",
        friendly_name="Anti-Crease No Steam",
    ),
    "userSelections/EWX1493A_anticreaseWSteam": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:hanger",
        friendly_name="Anti-Crease With Steam",
    ),
    "userSelections/EWX1493A_nightCycle": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:moon-waning-crescent",
        friendly_name="Night Cycle",
    ),
    "userSelections/EWX1493A_wmEconomy": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:cash",
        friendly_name="Economy Mode",
    ),
    "userSelections/EWX1493A_rinseHold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-pause",
        friendly_name="Rinse Hold",
    ),
    "userSelections/EWX1493A_intensive": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:power-high",
        friendly_name="Intensive Wash",
    ),
    "userSelections/EWX1493A_tcSensor": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Temperature Sensor",
    ),
    "userSelections/EWX1493A_stain": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:sticker-remove",
        friendly_name="Stain Action",
    ),
    "userSelections/EWX1493A_dryMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:tumble-dryer",
        friendly_name="Dry Mode",
    ),
    "userSelections/EWX1493A_easyIron": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:iron",
        friendly_name="Easy Iron",
    ),
    "userSelections/EWX1493A_pod": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:cube-outline",
        friendly_name="Pod Wash",
    ),
    "userSelections/EWX1493A_steamMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-partly-cloudy",
        friendly_name="Steam Mode",
    ),
    "userSelections/EWX1493A_ultraMix": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:rotate-3d-variant",
        friendly_name="Ultra Mix",
    ),
    "userSelections/EWX1493A_wetMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water",
        friendly_name="Wet Mode",
    ),
    "waterHardness": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "HARD": {},
                "MEDIUM": {},
                "SOFT": {},
                "STEP_1": {},
                "STEP_2": {},
                "STEP_3": {},
                "STEP_4": {},
                "STEP_5": {},
                "STEP_6": {},
                "STEP_7": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:water",
        friendly_name="Water Hardness",
    ),
    "waterSoftenerMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "ALWAYS": {},
                "WASH_ONLY": {},
                "DISABLED": {},
                "WASH_AND_RINSE": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:water-softener",
        friendly_name="Water Softener Mode",
    ),
    "displayLight": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DISPLAY_LIGHT_0": {},
                "DISPLAY_LIGHT_1": {},
                "DISPLAY_LIGHT_2": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:lightbulb",
        friendly_name="Display Light",
    ),
    # Maintenance system — group 0 (items 1–5)
    "applianceCareAndMaintenance0/maint1_ID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench",
        friendly_name="Maintenance Item 1 ID",
    ),
    "applianceCareAndMaintenance0/maint1_occured": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle",
        friendly_name="Maintenance Item 1 Occurred",
    ),
    "applianceCareAndMaintenance0/maint1_threshold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:gauge",
        friendly_name="Maintenance Item 1 Threshold",
    ),
    "applianceCareAndMaintenance0/maint2_ID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench",
        friendly_name="Maintenance Item 2 ID",
    ),
    "applianceCareAndMaintenance0/maint2_occured": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle",
        friendly_name="Maintenance Item 2 Occurred",
    ),
    "applianceCareAndMaintenance0/maint2_threshold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:gauge",
        friendly_name="Maintenance Item 2 Threshold",
    ),
    "applianceCareAndMaintenance0/maint3_ID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench",
        friendly_name="Maintenance Item 3 ID",
    ),
    "applianceCareAndMaintenance0/maint3_occured": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle",
        friendly_name="Maintenance Item 3 Occurred",
    ),
    "applianceCareAndMaintenance0/maint3_threshold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:gauge",
        friendly_name="Maintenance Item 3 Threshold",
    ),
    "applianceCareAndMaintenance0/maint4_ID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench",
        friendly_name="Maintenance Item 4 ID",
    ),
    "applianceCareAndMaintenance0/maint4_occured": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle",
        friendly_name="Maintenance Item 4 Occurred",
    ),
    "applianceCareAndMaintenance0/maint4_threshold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:gauge",
        friendly_name="Maintenance Item 4 Threshold",
    ),
    "applianceCareAndMaintenance0/maint5_ID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench",
        friendly_name="Maintenance Item 5 ID",
    ),
    "applianceCareAndMaintenance0/maint5_occured": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle",
        friendly_name="Maintenance Item 5 Occurred",
    ),
    "applianceCareAndMaintenance0/maint5_threshold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:gauge",
        friendly_name="Maintenance Item 5 Threshold",
    ),
    # Maintenance system — group 1 (items 6–10)
    "applianceCareAndMaintenance1/maint6_ID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench",
        friendly_name="Maintenance Item 6 ID",
    ),
    "applianceCareAndMaintenance1/maint6_occured": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle",
        friendly_name="Maintenance Item 6 Occurred",
    ),
    "applianceCareAndMaintenance1/maint6_threshold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:gauge",
        friendly_name="Maintenance Item 6 Threshold",
    ),
    "applianceCareAndMaintenance1/maint7_ID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench",
        friendly_name="Maintenance Item 7 ID",
    ),
    "applianceCareAndMaintenance1/maint7_occured": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle",
        friendly_name="Maintenance Item 7 Occurred",
    ),
    "applianceCareAndMaintenance1/maint7_threshold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:gauge",
        friendly_name="Maintenance Item 7 Threshold",
    ),
    "applianceCareAndMaintenance1/maint8_ID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench",
        friendly_name="Maintenance Item 8 ID",
    ),
    "applianceCareAndMaintenance1/maint8_occured": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle",
        friendly_name="Maintenance Item 8 Occurred",
    ),
    "applianceCareAndMaintenance1/maint8_threshold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:gauge",
        friendly_name="Maintenance Item 8 Threshold",
    ),
    "applianceCareAndMaintenance1/maint9_ID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench",
        friendly_name="Maintenance Item 9 ID",
    ),
    "applianceCareAndMaintenance1/maint9_occured": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle",
        friendly_name="Maintenance Item 9 Occurred",
    ),
    "applianceCareAndMaintenance1/maint9_threshold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:gauge",
        friendly_name="Maintenance Item 9 Threshold",
    ),
    "applianceCareAndMaintenance1/maint10_ID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench",
        friendly_name="Maintenance Item 10 ID",
    ),
    "applianceCareAndMaintenance1/maint10_occured": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle",
        friendly_name="Maintenance Item 10 Occurred",
    ),
    "applianceCareAndMaintenance1/maint10_threshold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:gauge",
        friendly_name="Maintenance Item 10 Threshold",
    ),
    # Miscellaneous state sensors
    "fCMiscellaneousState/detergentExtradosage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:cup-water",
        friendly_name="Detergent Extradosage",
    ),
    "fCMiscellaneousState/optisenseResult": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.WEIGHT,
        unit=UnitOfMass.GRAMS,
        entity_category=None,
        entity_icon="mdi:weight",
        friendly_name="Load Weight",
    ),
    "fCMiscellaneousState/softenerExtradosage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:cup-water",
        friendly_name="Softener Extradosage",
    ),
    "fCMiscellaneousState/tankADetLoadForNominalWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank A Load for Nominal Weight",
    ),
    "fCMiscellaneousState/tankAReserve": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask-outline",
        friendly_name="Tank A Reserve",
    ),
    "fCMiscellaneousState/tankBDetLoadForNominalWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank B Load for Nominal Weight",
    ),
    "fCMiscellaneousState/tankBReserve": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask-outline",
        friendly_name="Tank B Reserve",
    ),
    "fCMiscellaneousState/waterUsage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.WATER,
        unit=UnitOfVolume.LITERS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water",
        friendly_name="Water Usage",
    ),
    "fCMiscellaneousState/adTankADetLoaded": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank A Detergent Loaded",
    ),
    "fCMiscellaneousState/adTankBDetLoaded": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank B Detergent Loaded",
    ),
    "fCMiscellaneousState/adTankBSoftLoaded": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask-outline",
        friendly_name="Tank B Softener Loaded",
    ),
    "fCMiscellaneousState/ecoLevel": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:leaf",
        friendly_name="Eco Level",
    ),
    # Appliance software versions
    "applianceMainBoardSwVersion": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:chip",
        friendly_name="Main Board SW Version",
        entity_registry_enabled_default=False,
    ),
    "applianceUiSwVersion": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:application-cog",
        friendly_name="UI SW Version",
        entity_registry_enabled_default=False,
    ),
    # Appliance mode
    "applianceMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DEMO": {},
                "DIAGNOSTIC": {},
                "NORMAL": {},
                "SERVICE": {},
            },
        },
        device_class=SensorDeviceClass.ENUM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:cog",
        friendly_name="Appliance Mode",
        entity_registry_enabled_default=False,
    ),
    # Network settings
    "networkInterfaceAlwaysOn": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:wifi-check",
        friendly_name="Network Always On",
    ),
    "remoteNotificationPending": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:bell-ring",
        friendly_name="Remote Notification Pending",
        entity_registry_enabled_default=False,
    ),
    # Timing
    "minFinishInTime": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "number",
            "values": {"INVALID_OR_NOT_SET_TIME": {}},
        },
        device_class=None,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:clock-end",
        friendly_name="Min Finish In Time",
        entity_registry_enabled_default=False,
    ),
    # Auto dosing local fine tuning
    "autoDosing/adLocalFineTuning": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:tune",
        friendly_name="Auto Dose Local Fine Tuning",
    ),
    # Clear cycle personalization command
    "clearCyclePersonalizationCmd": ElectroluxDevice(
        capability_info={
            "access": "write",
            "type": "number",
            "values": {"0": {}},
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:restore",
        friendly_name="Clear Cycle Personalization",
        entity_registry_enabled_default=False,
    ),
    # Memory slot selection
    "userSelections/memoryId": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "number",
            "values": {
                "10": {},
                "20": {},
                "30": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:memory",
        friendly_name="Memory Slot",
    ),
    # Cycle personalization entries
    "cyclePersonalization/EWX1493A_anticreaseNoSteam": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:iron",
        friendly_name="Anti-crease (No Steam)",
    ),
    "cyclePersonalization/EWX1493A_anticreaseWSteam": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:iron-outline",
        friendly_name="Anti-crease (With Steam)",
    ),
    "cyclePersonalization/EWX1493A_nightCycle": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-night",
        friendly_name="Night Cycle",
    ),
    "cyclePersonalization/EWX1493A_preWashPhase": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-sync",
        friendly_name="Pre-wash Phase",
    ),
    "cyclePersonalization/EWX1493A_rinseHold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-pause",
        friendly_name="Rinse Hold",
    ),
    "cyclePersonalization/EWX1493A_stain": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:sticker-alert",
        friendly_name="Stain Removal",
    ),
    "cyclePersonalization/EWX1493A_tcSensor": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer-water",
        friendly_name="Temperature Care Sensor",
    ),
    "cyclePersonalization/EWX1493A_wmEconomy": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:leaf",
        friendly_name="Economy Mode",
        entity_registry_enabled_default=False,
    ),
    "cyclePersonalization/adFineTuneDetLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "FINE_TUNE_DET_LEV_1": {},
                "FINE_TUNE_DET_LEV_3": {},
                "FINE_TUNE_DET_LEV_5": {},
                "FINE_TUNE_DET_NOT_AVAILABLE": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:tune",
        friendly_name="Auto Dose Detergent Fine Tune",
    ),
    "cyclePersonalization/adFineTuneSoftLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "FINE_TUNE_SOFT_LEV_1": {},
                "FINE_TUNE_SOFT_NOT_AVAILABLE": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:tune",
        friendly_name="Auto Dose Softener Fine Tune",
    ),
    "cyclePersonalization/adTankASel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                AUTODOSE_DETERGENT_DUAL_OFF: {},
                AUTODOSE_DETERGENT_DUAL_ON: {},
                AUTODOSE_LINK_OFF: {},
                AUTODOSE_LINK_ON: {},
                AUTODOSE_OFF: {},
                AUTODOSE_SOFTENER_OFF: {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:flask-empty",
        friendly_name="Tank A Auto Dose Selection",
    ),
    "cyclePersonalization/adTankBSel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                AUTODOSE_DETERGENT_DUAL_OFF: {},
                AUTODOSE_DETERGENT_DUAL_ON: {},
                AUTODOSE_LINK_OFF: {},
                AUTODOSE_LINK_ON: {},
                AUTODOSE_OFF: {},
                AUTODOSE_SOFTENER_OFF: {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:flask",
        friendly_name="Tank B Auto Dose Selection",
    ),
    "cyclePersonalization/analogSpinSpeed": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "0_RPM": {},
                "400_RPM": {},
                "1000_RPM": {},
                "1200_RPM": {},
                "1400_RPM": {},
                "1600_RPM": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:rotate-orbit",
        friendly_name="Spin Speed",
    ),
    "cyclePersonalization/analogTemperature": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "20_CELSIUS": {},
                "30_CELSIUS": {},
                "40_CELSIUS": {},
                "50_CELSIUS": {},
                "60_CELSIUS": {},
                "95_CELSIUS": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Temperature",
    ),
    "cyclePersonalization/extraRinseNumber": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "NONE": {},
                "PLUS_1_RINSE": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-plus",
        friendly_name="Extra Rinse",
    ),
    "cyclePersonalization/programUID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
        friendly_name="Cycle Program",
    ),
    "cyclePersonalization/steamValue": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "STEAM_MAX": {},
                "STEAM_MED": {},
                "STEAM_MIN": {},
                "STEAM_OFF": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-fog",
        friendly_name="Steam Level",
    ),
    "cyclePersonalization/timeManagerLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DAILY": {},
                "NORMAL": {},
                "SUPER_QUICK": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:speedometer",
        friendly_name="Time Manager",
    ),
    # -----------------------------------------------------------------------
    # User selections – generic boolean options (no model-specific prefix)
    # e.g. model 914580416 reports these without the EWX1493A_ prefix
    # -----------------------------------------------------------------------
    "userSelections/anticreaseNoSteam": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:hanger",
        friendly_name="Anti-Crease No Steam",
    ),
    "userSelections/anticreaseWSteam": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:hanger",
        friendly_name="Anti-Crease With Steam",
    ),
    "userSelections/ultraMix": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:rotate-3d-variant",
        friendly_name="Ultra Mix",
    ),
    "userSelections/preWashPhase": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-plus",
        friendly_name="Pre-Wash",
    ),
    "userSelections/stain": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:sticker-remove",
        friendly_name="Stain Action",
    ),
    "userSelections/nightCycle": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:moon-waning-crescent",
        friendly_name="Night Cycle",
    ),
    "userSelections/wmEconomy": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:cash",
        friendly_name="Economy Mode",
    ),
    "userSelections/rinseHold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-pause",
        friendly_name="Rinse Hold",
    ),
    "userSelections/tcSensor": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Temperature Care Sensor",
    ),
    "userSelections/soak": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water",
        friendly_name="Soak",
    ),
    "userSelections/softener": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:bottle-tonic-outline",
        friendly_name="Softener",
    ),
    # -----------------------------------------------------------------------
    # Language setting
    # -----------------------------------------------------------------------
    "language": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "CHINESE": {},
                "DUTCH": {},
                "ENGLISH": {},
                "FRENCH": {},
                "GERMAN": {},
                "ITALIAN": {},
                "PORTUGUESE": {},
                "RUSSIAN": {},
                "SPANISH": {},
                "TURKISH": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:translate",
        friendly_name="Language",
        entity_registry_enabled_default=False,
    ),
    # -----------------------------------------------------------------------
    # Miscellaneous user settings
    # -----------------------------------------------------------------------
    "miscellaneous/defaultSoftPlus": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:bottle-tonic-plus",
        friendly_name="Default Soft Plus",
    ),
    # -----------------------------------------------------------------------
    # Appliance care and maintenance (diagnostic)
    # -----------------------------------------------------------------------
    "applianceCareAndMaintenance0/1/occured": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench-clock",
        friendly_name="Maintenance 1 Occurred",
    ),
    "applianceCareAndMaintenance0/1/threshold": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Maintenance 1 Threshold",
    ),
    "applianceCareAndMaintenance0/2/occured": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench-clock",
        friendly_name="Maintenance 2 Occurred",
    ),
    "applianceCareAndMaintenance0/2/threshold": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Maintenance 2 Threshold",
    ),
    "applianceCareAndMaintenance0/3/occured": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench-clock",
        friendly_name="Maintenance 3 Occurred",
    ),
    "applianceCareAndMaintenance0/3/threshold": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Maintenance 3 Threshold",
    ),
    "applianceCareAndMaintenance0/4/occured": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench-clock",
        friendly_name="Maintenance 4 Occurred",
    ),
    "applianceCareAndMaintenance0/4/threshold": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Maintenance 4 Threshold",
    ),
    "applianceCareAndMaintenance0/5/occured": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench-clock",
        friendly_name="Maintenance 5 Occurred",
    ),
    "applianceCareAndMaintenance0/5/threshold": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Maintenance 5 Threshold",
    ),
    "applianceCareAndMaintenance1/6/occured": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench-clock",
        friendly_name="Maintenance 6 Occurred",
    ),
    "applianceCareAndMaintenance1/6/threshold": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Maintenance 6 Threshold",
    ),
    "applianceCareAndMaintenance1/7/occured": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench-clock",
        friendly_name="Maintenance 7 Occurred",
    ),
    "applianceCareAndMaintenance1/7/threshold": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Maintenance 7 Threshold",
    ),
    "applianceCareAndMaintenance1/8/occured": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench-clock",
        friendly_name="Maintenance 8 Occurred",
    ),
    "applianceCareAndMaintenance1/8/threshold": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Maintenance 8 Threshold",
    ),
    "applianceCareAndMaintenance1/9/occured": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench-clock",
        friendly_name="Maintenance 9 Occurred",
    ),
    "applianceCareAndMaintenance1/9/threshold": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Maintenance 9 Threshold",
    ),
    "applianceCareAndMaintenance1/10/occured": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench-clock",
        friendly_name="Maintenance 10 Occurred",
    ),
    "applianceCareAndMaintenance1/10/threshold": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Maintenance 10 Threshold",
    ),
    "applianceCareAndMaintenance2/11/occured": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench-clock",
        friendly_name="Maintenance 11 Occurred",
    ),
    "applianceCareAndMaintenance2/11/threshold": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Maintenance 11 Threshold",
    ),
    "applianceCareAndMaintenance3/16/occured": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench-clock",
        friendly_name="Maintenance 16 Occurred",
    ),
    "applianceCareAndMaintenance3/16/threshold": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Maintenance 16 Threshold",
    ),
    # -----------------------------------------------------------------------
    # Additional network interface information
    # -----------------------------------------------------------------------
    "networkInterface/autoLocalTimeOffset": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:clock",
        friendly_name="Auto Local Time Offset",
    ),
    "networkInterface/niuSwUpdateCurrentDescription": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:update",
        friendly_name="NIU SW Update Description",
    ),
    "networkInterface/swAncAndRevision": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:chip",
        friendly_name="SW ANC and Revision",
    ),
    "networkInterface/timeZoneDatabaseName": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:earth",
        friendly_name="Time Zone Database",
    ),
    # -----------------------------------------------------------------------
    # Additional appliance information
    # -----------------------------------------------------------------------
    "applianceInfo/applianceType": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:information",
        friendly_name="Appliance Type",
    ),
    "applianceInfo/capabilityHash": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:identifier",
        friendly_name="Capability Hash",
    ),
    "cpv": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:tag",
        friendly_name="CPV",
    ),
    "totalSteamCycleCounter": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Total Steam Cycle Counter",
    ),
}
