"""Defined catalog of entities for refrigerator type devices."""

from homeassistant.components.binary_sensor import BinarySensorDeviceClass
from homeassistant.components.number import NumberDeviceClass
from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.components.switch import SwitchDeviceClass
from homeassistant.const import EntityCategory, UnitOfTemperature, UnitOfTime

from ..const import BINARY_SENSOR, BUTTON, SELECT, SWITCH
from ..model import ElectroluxDevice

CATALOG_CR: dict[str, ElectroluxDevice] = {
    "freezer/alerts": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert",
    ),
    "freezer/applianceState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"OFF": {}, "RUNNING": {}},
        },
        device_class=BinarySensorDeviceClass.RUNNING,
        unit=None,
        entity_category=None,
        friendly_name="Freezer State",
    ),
    "freezer/doorState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"CLOSED": {}, "OPEN": {}},
        },
        device_class=BinarySensorDeviceClass.OPENING,
        unit=None,
        entity_category=None,
    ),
    "freezer/fastMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:fridge-variant",
    ),
    "freezer/fastModeTimeToEnd": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.TIMESTAMP,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:timer-outline",
    ),
    "freezer/sensorTemperatureC": ElectroluxDevice(
        capability_info={"access": "read", "type": "temperature"},
        device_class=SensorDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Freezer Temperature",
    ),
    "freezer/targetTemperatureC": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": -18.0,
            "max": -13.0,
            "min": -23.0,
            "step": 1.0,
            "type": "temperature",
        },
        device_class=NumberDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        entity_category=None,
        entity_icon="mdi:thermometer",
    ),
    "fridge/alerts": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert",
    ),
    "fridge/applianceState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"OFF": {}, "RUNNING": {}},
        },
        device_class=BinarySensorDeviceClass.RUNNING,
        unit=None,
        entity_category=None,
        friendly_name="Fridge State",
    ),
    "fridge/doorState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"CLOSED": {}, "OPEN": {}},
        },
        device_class=BinarySensorDeviceClass.OPENING,
        unit=None,
        entity_category=None,
    ),
    "fridge/fastMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:fridge-variant",
    ),
    "fridge/fastModeTimeToEnd": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.TIMESTAMP,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:timer-outline",
    ),
    "fridge/sensorTemperatureC": ElectroluxDevice(
        capability_info={"access": "read", "type": "temperature"},
        device_class=SensorDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Fridge Temperature",
    ),
    "fridge/targetTemperatureC": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 4.0,
            "max": 7.0,
            "min": 1.0,
            "step": 1.0,
            "type": "temperature",
        },
        device_class=NumberDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        entity_category=None,
        entity_icon="mdi:thermometer",
    ),
    # Main appliance controls
    "sabbathMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:star-david",
        friendly_name="Sabbath Mode",
    ),
    "vacationHolidayMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:beach",
        friendly_name="Vacation Mode",
    ),
    # Sensors
    "sensorHumidity": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.HUMIDITY,
        unit="%",
        entity_category=None,
        entity_icon="mdi:water-percent",
        friendly_name="Humidity",
    ),
    # Filter monitoring
    "waterFilterState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"GOOD": {}, "CLEAN": {}, "CHANGE": {}, "BUY": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water",
        friendly_name="Water Filter Status",
    ),
    "waterFilterStateReset": ElectroluxDevice(
        capability_info={
            "access": "write",
            "type": "string",
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_platform=BUTTON,
        entity_icon="mdi:water",
        friendly_name="Reset Water Filter",
    ),
    "waterFilterLifeTime": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water",
        friendly_name="Water Filter Life Time",
    ),
    "waterFilterFlow": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.WATER,
        unit="L",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water",
        friendly_name="Water Filter Flow",
    ),
    "airFilterState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"GOOD": {}, "CLEAN": {}, "CHANGE": {}, "BUY": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:air-filter",
        friendly_name="Air Filter Status",
    ),
    "airFilterStateReset": ElectroluxDevice(
        capability_info={
            "access": "write",
            "type": "string",
        },
        device_class=None,
        unit=None,
        entity_platform=BUTTON,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:air-filter",
        friendly_name="Reset Air Filter",
    ),
    "airFilterLifeTime": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:air-filter",
        friendly_name="Air Filter Life Time",
    ),
    # Additional sensors and controls
    "coolingValveState": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:valve",
        friendly_name="Cooling Valve State",
    ),
    "defrostRoutineState": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:snowflake-melt",
        friendly_name="Defrost Routine State",
    ),
    "compressorState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=BinarySensorDeviceClass.RUNNING,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        friendly_name="Compressor State",
    ),
    "compressorSpeed": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="rpm",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:fan",
        friendly_name="Compressor Speed",
    ),
    "compressorSpeed/coefficient": ElectroluxDevice(
        capability_info={"access": "read", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:fan",
        friendly_name="Compressor Speed Coefficient",
        entity_registry_enabled_default=False,
    ),
    "compressorSpeed/exponent": ElectroluxDevice(
        capability_info={"access": "read", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:fan",
        friendly_name="Compressor Speed Exponent",
        entity_registry_enabled_default=False,
    ),
    "reminderTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 1200,
            "max": 2700,
            "min": 1200,
            "step": 60,
            "type": "number",
        },
        device_class=NumberDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=None,
        entity_icon="mdi:clock",
        friendly_name="Reminder Time",
    ),
    # Extra cavity (wine cellar, etc.)
    "extraCavity/alerts": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert",
        friendly_name="Extra Cavity Alerts",
    ),
    "extraCavity/applianceState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"OFF": {}, "RUNNING": {}},
        },
        device_class=BinarySensorDeviceClass.RUNNING,
        unit=None,
        entity_category=None,
        friendly_name="Extra Cavity State",
    ),
    "extraCavity/doorState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"CLOSED": {}, "OPEN": {}},
        },
        device_class=BinarySensorDeviceClass.OPENING,
        unit=None,
        entity_category=None,
        friendly_name="Extra Cavity Door",
    ),
    "extraCavity/fanState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "number",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=BinarySensorDeviceClass.RUNNING,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        friendly_name="Extra Cavity Fan State",
    ),
    "extraCavity/cloneTargetTemperatureMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"OFF": {}, "FREEZER": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Extra Cavity Clone Mode",
    ),
    "extraCavity/targetTemperatureC": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "temperature",
            "values": {"-2.0": {}, "0.0": {}, "3.0": {}, "7.0": {}},
        },
        device_class=None,
        unit=UnitOfTemperature.CELSIUS,
        entity_category=None,
        entity_platform=SELECT,
        entity_icon="mdi:thermometer",
        friendly_name="Extra Cavity Temperature",
    ),
    "extraCavity/sensorTemperatureC": ElectroluxDevice(
        capability_info={"access": "read", "type": "temperature"},
        device_class=SensorDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Extra Cavity Sensor Temperature",
    ),
    "extraCavity/temperatureAdjustingState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "number",
            "values": {"DOWN": {}, "NONE": {}, "UP": {}},
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:thermometer",
        friendly_name="Extra Cavity Adjusting",
    ),
    # Ice maker
    "iceMaker/alerts": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert",
        friendly_name="Ice Maker Alerts",
    ),
    "iceMaker/applianceState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"OFF": {}, "RUNNING": {}},
        },
        device_class=BinarySensorDeviceClass.RUNNING,
        unit=None,
        entity_category=None,
        friendly_name="Ice Maker State",
    ),
    "iceMaker/executeCommand": ElectroluxDevice(
        capability_info={
            "access": "write",
            "type": "string",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:power",
        friendly_name="Ice Maker Control",
    ),
    "iceMaker/defrostTemperatureC": ElectroluxDevice(
        capability_info={"access": "read", "type": "temperature"},
        device_class=SensorDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        entity_category=None,
        entity_icon="mdi:snowflake-thermometer",
        friendly_name="Ice Maker Defrost Temperature",
    ),
    "iceMaker/sensorTemperatureC": ElectroluxDevice(
        capability_info={"access": "read", "type": "temperature"},
        device_class=SensorDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Ice Maker Temperature",
    ),
    "iceMaker/evaporatorFanState": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:fan",
        friendly_name="Ice Maker Fan State",
    ),
    "iceMaker/iceDispenserState": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:cup-water",
        friendly_name="Ice Dispenser State",
    ),
    "iceMaker/iceTrayWaterFillSetting": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "number",
            "values": {
                "VERY_LOW_PRESSURE": {},
                "LOW_PRESSURE": {},
                "NORMAL_PRESSURE": {},
                "VERY_HIGH_PRESSURE": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:tray",
        friendly_name="Ice Tray Fill Setting",
    ),
    # Filter maintenance thresholds (constants from device)
    "airFilterLifeTimeBuyThreshold": ElectroluxDevice(
        capability_info={
            "access": "constant",
            "type": "number",
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:air-filter",
        entity_registry_enabled_default=False,
        friendly_name="Air Filter Buy Threshold",
    ),
    "airFilterLifeTimeChangeThreshold": ElectroluxDevice(
        capability_info={
            "access": "constant",
            "type": "number",
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:air-filter",
        entity_registry_enabled_default=False,
        friendly_name="Air Filter Change Threshold",
    ),
    "waterFilterFlowBuyThreshold": ElectroluxDevice(
        capability_info={
            "access": "constant",
            "type": "number",
        },
        device_class=SensorDeviceClass.WATER,
        unit="L",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water-pump",
        entity_registry_enabled_default=False,
        friendly_name="Water Filter Buy Threshold (Flow)",
    ),
    "waterFilterFlowChangeThreshold": ElectroluxDevice(
        capability_info={
            "access": "constant",
            "type": "number",
        },
        device_class=SensorDeviceClass.WATER,
        unit="L",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water-pump",
        entity_registry_enabled_default=False,
        friendly_name="Water Filter Change Threshold (Flow)",
    ),
    "waterFilterLifeTimeBuyThreshold": ElectroluxDevice(
        capability_info={
            "access": "constant",
            "type": "number",
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water-pump",
        entity_registry_enabled_default=False,
        friendly_name="Water Filter Buy Threshold (Time)",
    ),
    "waterFilterLifeTimeChangeThreshold": ElectroluxDevice(
        capability_info={
            "access": "constant",
            "type": "number",
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water-pump",
        entity_registry_enabled_default=False,
        friendly_name="Water Filter Change Threshold (Time)",
    ),
    "applianceMainBoardSwVersion": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:chip",
        entity_registry_enabled_default=False,
        friendly_name="Main Board Software Version",
    ),
    "ecoMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 1,
            "type": "enum",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=None,
        entity_platform=SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:leaf",
        friendly_name="Eco Mode",
    ),
    "autosense": ElectroluxDevice(
        capability_info={
            "access": "constant",
            "default": 0,
            "type": "enum",
            "values": {"0": {}, "1": {}},
        },
        device_class=None,
        entity_platform=BINARY_SENSOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:autorenew",
        entity_registry_enabled_default=False,
        friendly_name="Autosense",
    ),
    "applianceMode": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "DEMO": {},
                "NORMAL": {},
                "SERVICE": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench",
        entity_registry_enabled_default=False,
        friendly_name="Appliance Mode",
    ),
    # Dual child lock controls — models with two separate door locks (e.g. EHE6899SA/BA)
    # report both keys; single-lock models only report uiLockMode and ignore ui2LockMode.
    "uiLockMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:lock",
        friendly_name="Child Lock Internal",
    ),
    "ui2LockMode": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "boolean",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=BinarySensorDeviceClass.LOCK,
        unit=None,
        entity_category=None,
        entity_icon="mdi:lock-outline",
        friendly_name="Child Lock External",
    ),
}
